#!/usr/bin/env python3
"""Build a promptfoo config from the question-router skill files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REFERENCE_ORDER = ["learning", "analysis", "decision", "plan", "risk", "technical"]


def skill_root() -> Path:
    return Path(__file__).resolve().parents[1]


def yaml_block(text: str, indent: int = 4) -> str:
    prefix = " " * indent
    return "\n".join(prefix + line if line else prefix for line in text.rstrip().splitlines())


def yaml_scalar(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_prompt(root: Path) -> str:
    parts = [
        "You are a question-routing assistant. Follow the bundled question-router skill exactly.",
        "",
        "## SKILL.md",
        (root / "SKILL.md").read_text(encoding="utf-8"),
    ]
    for name in REFERENCE_ORDER:
        rel = f"references/{name}.md"
        parts.extend(["", f"## {rel}", (root / rel).read_text(encoding="utf-8")])
    parts.extend(["", "User question: {{question}}"])
    return "\n".join(parts)


def build_assertions(case: dict[str, object]) -> list[dict[str, str]]:
    assertions: list[dict[str, str]] = [
        {"type": "icontains", "value": str(case["expectedType"])}
    ]
    for value in case.get("mustInclude", []):
        assertions.append({"type": "icontains", "value": str(value)})
    for value in case.get("mustAvoid", []):
        assertions.append({"type": "not-icontains", "value": str(value)})
    if case.get("shouldClarify") is True:
        assertions.append({"type": "contains", "value": "?"})
    return assertions


def render_config(root: Path, provider_url: str, model: str, max_tokens: int, temperature: float) -> str:
    evals = json.loads((root / "evals/evals.json").read_text(encoding="utf-8"))
    prompt = build_prompt(root)

    lines = [
        "# Generated by question-router/scripts/build_promptfoo_config.py",
        'description: "Generated question-router skill evals"',
        "",
        "providers:",
        "  - id: http",
        "    config:",
        f"      url: {provider_url}",
        "      method: POST",
        "      headers:",
        "        Content-Type: application/json",
        '        x-api-key: "{{env.ANTHROPIC_AUTH_TOKEN}}"',
        '        anthropic-version: "2023-06-01"',
        "      body:",
        f"        model: {model}",
        f"        max_tokens: {max_tokens}",
        f"        temperature: {temperature}",
        "        messages:",
        "          - role: user",
        "            content:",
        "              - type: text",
        '                text: "{{prompt}}"',
        "      transformResponse: json.content.filter(function(c) { return c.type === 'text'; }).map(function(c) { return c.text; }).join('\\n')",
        "",
        "prompts:",
        "  - |-" ,
        yaml_block(prompt, indent=4),
        "",
        "tests:",
    ]

    for case in evals:
        lines.extend([
            f"  - description: {yaml_scalar(case['id'] + ': ' + case['notes'])}",
            "    vars:",
            f"      question: {yaml_scalar(case['question'])}",
            "    assert:",
        ])
        for assertion in build_assertions(case):
            lines.extend([
                "      - type: " + assertion["type"],
                "        value: " + yaml_scalar(assertion["value"]),
            ])

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a promptfoo config for question-router evals.")
    parser.add_argument("--output", default="/Users/chen/skill-test/promptfoo-tests/promptfooconfig.generated.yaml")
    parser.add_argument("--provider-url", default="https://ark.cn-beijing.volces.com/api/coding/v1/messages")
    parser.add_argument("--model", default="deepseek-v4-pro")
    parser.add_argument("--max-tokens", type=int, default=2048)
    parser.add_argument("--temperature", type=float, default=0.3)
    args = parser.parse_args()

    root = skill_root()
    output = Path(args.output).expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_config(root, args.provider_url, args.model, args.max_tokens, args.temperature),
        encoding="utf-8",
    )
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
